/************************************************************\
 **  Copyright (c) 2012-2024 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	D:/my_project/O__Verimake__DEMO__PH1A90/sgdma_prj_90k/src/sgdma_ip/ip/dram32x13.v
 ** Date	:	2024 09 09
 ** TD version	:	6.0.122666
\************************************************************/

`timescale 1 ns / 1 ps

module dram32x13 ( di, waddr, we, wclk, rdo, raddr );

	parameter DATA_WIDTH_W = 13; 
	parameter ADDR_WIDTH_W = 5;
	parameter DATA_DEPTH_W = 32;
	parameter DATA_WIDTH_R = 13;
	parameter ADDR_WIDTH_R = 5;
	parameter DATA_DEPTH_R = 32;

	input  [DATA_WIDTH_W-1:0] di;
	input  [ADDR_WIDTH_W-1:0] waddr;
	input  [ADDR_WIDTH_R-1:0] raddr;
	input  wclk,we;

	output [DATA_WIDTH_R-1:0] rdo;



	PH1_LOGIC_DRAM #(
 			.INIT_FILE("NONE"),
			.FILL_ALL("NONE"),
			.READREG("DISABLE"),
			.DATA_WIDTH_W(DATA_WIDTH_W),
			.ADDR_WIDTH_W(ADDR_WIDTH_W),
			.DATA_DEPTH_W(DATA_DEPTH_W),
			.DATA_WIDTH_R(DATA_WIDTH_R),
			.ADDR_WIDTH_R(ADDR_WIDTH_R),
			.DATA_DEPTH_R(DATA_DEPTH_R))
		dram(
			.di(di),
			.waddr(waddr),
			.wclk(wclk),
			.we(we),
			.rclk(1'b0),
			.rrst(1'b0),
			.rce(1'b0),
			.rdoq(),
			.rdo(rdo),
			.raddr(raddr));

endmodule