--------------------------------------------------------------
 --  Copyright (c) 2012-2024 Anlogic Inc. --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	D:/my_project/O__Verimake__DEMO__PH1A90/sgdma_prj_90k/src/sgdma_ip/ip/dram32x13.vhd
 -- Date	:	2024 09 09
 -- TD version	:	6.0.122666
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY ph1_macro;
	USE ph1_macro.PH1_COMPONENTS.all;

ENTITY dram32x13 IS
PORT (
	rdo	: OUT STD_LOGIC_VECTOR(12 DOWNTO 0);

	di	: IN STD_LOGIC_VECTOR(12 DOWNTO 0);
	waddr: IN STD_LOGIC_VECTOR(4 DOWNTO 0);
	raddr	: IN STD_LOGIC_VECTOR(4 DOWNTO 0);
	we	: IN STD_LOGIC;
	wclk	: IN STD_LOGIC
	);
END dram32x13;

ARCHITECTURE struct OF dram32x13 IS

	BEGIN
	inst : PH1_LOGIC_DRAM
		GENERIC MAP (
			DATA_WIDTH_W	=> 13,
			ADDR_WIDTH_W	=> 5,
			DATA_DEPTH_W	=> 32,
			DATA_WIDTH_R	=> 13,
			ADDR_WIDTH_R	=> 5,
			DATA_DEPTH_R	=> 32,
			READREG			=> "DISABLE",
			FILL_ALL		=> "NONE",
			INIT_FILE		=> "NONE"
		)
		PORT MAP (
			di		=> di,
			waddr	=> waddr,
			we		=> we,
			wclk	=> wclk,
			rclk	=> '0',
			rrst	=> '0',
			rce		=> '0',
			rdoq	=> open,
			rdo		=> rdo,
			raddr	=> raddr
		);

END struct;
