
`timescale 1ns/100fs
/************************************************************\
 **  Copyright (c) 2012-2024 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	D:/my_project/O__Verimake__DEMO__PH1A90/sgdma/src/sgdma_ip/ip/pcie_ep_core_ph1_pcie_core_pll.v
 ** Date	:	2024 09 12
 ** TD version	:	6.0.122666
\************************************************************/
module pcie_ep_core_ph1_core_pll (refclk, 
        reset, 
        drp_clk, 
        drp_rstn, 
        drp_sel, 
        drp_rd, 
        drp_wr, 
        drp_addr, 
        drp_wdata, 
        lock, 
        drp_err, 
        drp_rdy, 
        drp_rdata, 
        clk0_out) ;
    input refclk ; 
    input reset ; 
    input drp_clk ; 
    input drp_rstn ; 
    input drp_sel ; 
    input drp_rd ; 
    input drp_wr ; 
    input [7:0] drp_addr ; 
    input [7:0] drp_wdata ; 
    output lock ; 
    output drp_err ; 
    output drp_rdy ; 
    output [7:0] drp_rdata ; 
    output clk0_out ; 
    wire clk0_buf ; 
    wire clk0_buf_sclk ; 
    PH1_LOGIC_BUFG bufg_feedback (.i(clk0_buf), 
                .o(clk0_out)) ; 
    PH1_PHY_SCLK_V2 #(.DELAY(0)) u_pll_fb_sclk (.ce(1'b1), 
                .clkin(clk0_out), 
                .clkout(clk0_buf_sclk)) ; 
    PH1_PHY_PLL #(.DYN_PHASE_PATH_SEL("DISABLE"),
            .DYN_FPHASE_EN("DISABLE"),
            .MPHASE_ENABLE("DISABLE"),
            .FIN("62.500"),
            .FEEDBK_MODE("NORMAL"),
            .FBKCLK("CLKC0_EXT"),
            .PLL_FEED_TYPE("EXTERNAL"),
            .PLL_USR_RST("ENABLE"),
            .GMC_GAIN(2),
            .ICP_CUR(12),
            .LPF_CAP(2),
            .LPF_RES(2),
            .REFCLK_DIV(1),
            .FBCLK_DIV(1),
            .CLKC0_ENABLE("ENABLE"),
            .CLKC0_DIV(16),
            .CLKC0_CPHASE(15),
            .CLKC0_FPHASE(0),
            .CLKC0_FPHASE_RSTSEL(0),
            .CLKC0_DUTY_INT(8),
            .CLKC0_DUTY50("ENABLE"),
            .CLKC1_ENABLE("ENABLE"),
            .CLKC1_DIV(16),
            .CLKC1_CPHASE(15),
            .CLKC1_FPHASE(0),
            .CLKC1_FPHASE_RSTSEL(0),
            .CLKC1_DUTY_INT(8),
            .CLKC1_DUTY50("ENABLE"),
            .INTPI(0),
            .HIGH_SPEED_EN("DISABLE"),
            .SSC_ENABLE("DISABLE"),
            .SSC_MODE("CENTER"),
            .SSC_AMP(0.0),
            .SSC_FREQ_DIV(0),
            .SSC_RNGE(0),
            .FRAC_ENABLE("DISABLE"),
            .DITHER_ENABLE("DISABLE"),
            .SDM_FRAC(0)) pll_inst (.refclk(refclk), 
                .pllreset(reset), 
                .lock(lock), 
                .pllpd(1'b0), 
                .refclk_rst(1'b0), 
                .wakeup(1'b0), 
                .psclk(1'b0), 
                .psdown(1'b0), 
                .psstep(1'b0), 
                .psclksel(3'b000), 
                .psdone(open), 
                .cps_step(2'b00), 
                .drp_clk(drp_clk), 
                .drp_rstn(drp_rstn), 
                .drp_sel(drp_sel), 
                .drp_rd(drp_rd), 
                .drp_wr(drp_wr), 
                .drp_addr(drp_addr), 
                .drp_wdata(drp_wdata), 
                .drp_err(drp_err), 
                .drp_rdy(drp_rdy), 
                .drp_rdata(drp_rdata), 
                .fbclk(clk0_buf_sclk), 
                .clkc({open,
                    open,
                    open,
                    open,
                    open,
                    open,
                    open,
                    clk0_buf}), 
                .clkcb({open,
                    open,
                    open,
                    open,
                    open,
                    open,
                    open,
                    open}), 
                .clkc_en({8'b00000011}), 
                .clkc_rst(2'b00), 
                .ext_freq_mod_clk(1'b0), 
                .ext_freq_mod_en(1'b0), 
                .ext_freq_mod_val(17'b00000000000000000), 
                .ssc_en(1'b0)) ; 
endmodule


