--------------------------------------------------------------
 --  Copyright (c) 2012-2024 Anlogic Inc. --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	D:/my_project/O__Verimake__DEMO__PH1A90/sgdma_prj_90k/src/sgdma_ip/ip/sfifo512x64.vhd
 -- Date	:	2024 09 09
 -- TD version	:	6.0.122666
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY ph1_macro;
	USE ph1_macro.PH1_COMPONENTS.all;

ENTITY sfifo512x64 IS
PORT (
    wrst	: IN STD_LOGIC;
    rrst	: IN STD_LOGIC;
    di	: IN STD_LOGIC_VECTOR(63 DOWNTO 0);

    clk	: IN STD_LOGIC;
    we	: IN STD_LOGIC;
    re	: IN STD_LOGIC;
    dout	: OUT STD_LOGIC_VECTOR(63 DOWNTO 0);

    empty_flag	: OUT STD_LOGIC;
    full_flag	: OUT STD_LOGIC;
    fifo_wrpointer	: OUT STD_LOGIC_VECTOR(8 DOWNTO 0);

    fifo_rdpointer	: OUT STD_LOGIC_VECTOR(8 DOWNTO 0)

);
END sfifo512x64;

ARCHITECTURE struct OF sfifo512x64 IS

    BEGIN
        fifo_inst : PH1_LOGIC_FIFO
            GENERIC MAP (
                DATA_WIDTH	=> 64,
                ADDR_WIDTH	=> 9,
                REGMODE_R	=> "OUTREG",
                FIRSTWRITE_RD	=> "DISABLE",
                ASYNC_RESET_RELEASE	=> "SYNC",
                CLKMODE	=> "SYNC",
                SSROVERCE	=> "DISABLE",
                ECC_ENCODE	=> "DISABLE",
                ECC_DECODE	=> "DISABLE"
            )
            PORT MAP (
			wrst	=> wrst,
			rrst	=> rrst,
			di	=> di,
			clkw	=> clk,
			we	=> we,
			csw	=> "111",
			clkr	=> clk,
			re	=> re,
			csr	=> "111",
			dout	=> dout,
			empty_flag	=> empty_flag,
			aempty_flag	=> OPEN,
			full_flag	=> full_flag,
			afull_flag	=> OPEN,
			ecc_sbiterr	=> OPEN,
			ecc_dbiterr	=> OPEN,
			fifo_wrpointer	=> fifo_wrpointer,
			fifo_rdpointer	=> fifo_rdpointer
            );

END struct;
